# Generated by Django 2.2.6 on 2020-02-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messadmin', '0003_messrules_mess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(help_text='e.g veg/ non veg/ jain', max_length=50)),
                ('details', models.TextField()),
                ('specifications', models.CharField(help_text='e.g Lunch, dinner only or breakfast, lunch, dinner', max_length=50)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messadmin.MessModel')),
            ],
        ),
    ]
