# Generated by Django 2.0 on 2020-02-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_products_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image3',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
