# Generated by Django 2.0 on 2020-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200227_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
    ]
