# Generated by Django 2.2.6 on 2020-02-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_messadmin',
            field=models.BooleanField(default=False),
        ),
    ]
