# Generated by Django 2.2.6 on 2020-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_launch_before', models.TimeField()),
                ('cancel_dinner_before', models.TimeField()),
                ('breakfast_from', models.TimeField()),
                ('breakfast_to', models.TimeField()),
                ('launchtime_from', models.TimeField()),
                ('launchtime_to', models.TimeField()),
                ('dinnertime_from', models.TimeField()),
                ('dinnertime_to', models.TimeField()),
            ],
        ),
    ]
