# Generated by Django 2.2.6 on 2020-02-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0002_messrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='messrules',
            name='mess',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='messadmin.MessModel'),
            preserve_default=False,
        ),
    ]
