# Generated by Django 2.2.6 on 2020-02-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messadmin', '0003_messrules_mess'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
